//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishersYMCA.Swimming.WebAPI.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    using FishersYMCA.Swimming.Domain;
    public partial class LaneAssignment : Entity
    {
        public LaneAssignment()
        {
            this.LaneAssignmentDetails = new HashSet<LaneAssignmentDetail>();
        }
    
        public int ID { get; set; }
        public string Lane { get; set; }
        public string Description { get; set; }
        public int SlotID { get; set; }
    
        public virtual ICollection<LaneAssignmentDetail> LaneAssignmentDetails { get; set; }
        public virtual PoolUsage PoolUsage { get; set; }
    }
}
