//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishersYMCA.Swimming.WebAPI.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    using FishersYMCA.Swimming.Domain;
    public partial class PoolUsage : Entity
    {
        public int ID { get; set; }
        public string Time { get; set; }
        public Nullable<int> Lane1 { get; set; }
        public Nullable<int> Lane2 { get; set; }
        public Nullable<int> Lane3 { get; set; }
        public Nullable<int> Lane4 { get; set; }
        public Nullable<int> Lane5 { get; set; }
        public Nullable<int> Lane6 { get; set; }
        public Nullable<int> Lane7 { get; set; }
        public string Day { get; set; }
    }
}
