//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishersYMCA.Swimming.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    using FishersYMCA.Swimming.Domain;
    public partial class LaneAssignment : Entity
    {
        public int ID { get; set; }
        public string Lane { get; set; }
        public string Description { get; set; }
        public int SlotID { get; set; }
        public string InstructorName { get; set; }
        public string InstructorPhone { get; set; }
        public string StudentPhone { get; set; }
        public string StudentName { get; set; }
        public string Category { get; set; }
    
        public virtual PoolUsage PoolUsage { get; set; }
    }
}
