//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishersYMCA.Swimming.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    using FishersYMCA.Swimming.Domain;
    public partial class PoolUsage : Entity
    {
        public PoolUsage()
        {
            this.LaneAssignments = new HashSet<LaneAssignment>();
        }
    
        public int ID { get; set; }
        public string Time { get; set; }
        public string Day { get; set; }
    
        public virtual ICollection<LaneAssignment> LaneAssignments { get; set; }
    }
}
