//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishersYMCA.Swimming.Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SwimDataEntities : DbContext
    {
        public SwimDataEntities()
            : base("name=SwimDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<LaneAssignment> LaneAssignments { get; set; }
        public DbSet<LaneAssignmentDetail> LaneAssignmentDetails { get; set; }
        public DbSet<PoolUsage> PoolUsages { get; set; }
    }
}
